'use client';
import { useEffect,useState } from 'react';
import { MapPin,Upload,X } from 'lucide-react';
import { categories,districts,officers,transitions,type Complaint,type Evidence } from '../lib/domain';
type Translate=(s:string)=>string;
export type SaveComplaint=(body:Record<string,unknown>|FormData,method?:string)=>Promise<boolean>;
function Dialog({children,close,title}:{children:React.ReactNode;close:()=>void;title:string}){
 useEffect(()=>{const before=document.activeElement as HTMLElement;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=Array.from(document.querySelectorAll<HTMLElement>('.dialog button:not(:disabled),.dialog a,.dialog input,.dialog select,.dialog textarea'));const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);document.body.style.overflow='hidden';(document.querySelector('.dialog button') as HTMLElement)?.focus();return()=>{document.removeEventListener('keydown',key);document.body.style.overflow='';before?.focus();};},[]);
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" className="icon-button" aria-label="Close / बंद करें" onClick={close}><X/></button></header>{children}</section></div>;
}
function LocationFields({t,c}:{t:Translate;c?:Complaint}){
 return <fieldset className="location-fields"><legend><MapPin size={15}/>{t('Complaint location')}</legend><label>{t('District')}<select name="district" defaultValue={c?.district||districts[0]}>{districts.map(d=><option key={d} value={d}>{t(d)}</option>)}</select></label><label>{t('Location / address')}<textarea name="address" required maxLength={500} defaultValue={c?.address} placeholder={t('Village / locality, ward, road and nearest landmark')}/></label><details className="coordinates" open={c?.latitude!=null}><summary>{t('Map coordinates (optional)')}</summary><div className="form-grid"><label>{t('Latitude')}<input name="latitude" type="number" step="any" min="-90" max="90" defaultValue={c?.latitude??''} placeholder="26.8467"/></label><label>{t('Longitude')}<input name="longitude" type="number" step="any" min="-180" max="180" defaultValue={c?.longitude??''} placeholder="80.9462"/></label></div><small>{t('Enter both coordinates, or leave both blank.')}</small></details></fieldset>;
}
function Photo({id,photo,t}:{id:string;photo:Evidence;t:Translate}){
 const [failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);
 const src=`/api/complaints/photo?complaint=${encodeURIComponent(id)}&photo=${encodeURIComponent(photo.id)}`;
 return <figure className="evidence-photo">{failed?<div className="photo-error">{t('Photo unavailable')}<button type="button" className="text-button" onClick={()=>{setFailed(false);setAttempt(attempt+1);}}>{t('Retry')}</button></div>:<a href={src} target="_blank" rel="noreferrer"><img key={attempt} src={src+(attempt?`&retry=${attempt}`:'')} alt={t('Photo of completed repair')} onError={()=>setFailed(true)}/></a>}<figcaption>{t('Resolution photo')} · {photo.name}</figcaption></figure>;
}
export function ComplaintDialog({c,t,date,sla,saving,close,save}:{c:Complaint;t:Translate;date:(s:string)=>string;sla:(c:Complaint)=>React.ReactNode;saving:boolean;close:()=>void;save:SaveComplaint}){
 const [status,setStatus]=useState(c.status),[officer,setOfficer]=useState(c.officer),[note,setNote]=useState(''),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState('');
 const resolving=status==='Resolved'&&c.status!=='Resolved';
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 const mapQuery=c.latitude!=null&&c.longitude!=null?`${c.latitude},${c.longitude}`:`${c.address}, ${c.district}, Uttar Pradesh`;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(resolving&&!photo){setError(t('A repair photo is required to resolve this complaint.'));return;}const form=new FormData(e.currentTarget);form.set('id',c.id);form.set('version',String(c.version));form.set('status',status);form.set('officer',officer);form.set('note',note);form.delete('photo');if(resolving&&photo)form.set('photo',photo);if(await save(form))setNote('');}
 return <Dialog close={close} title={t('Complaint details')}><div className="dialog-body"><span className="eyebrow">{c.id}</span><h2>{t(c.category)}</h2><p>{c.title}</p><div className="detail-fields">{[['Status',t(c.status)],['Priority',t(c.priority)],['Location',`${t(c.district)} · ${c.address}`],['Citizen',c.citizen],['Assigned officer',c.officer||t('Unassigned')],['Reported on',date(c.createdAt)],['Due by',date(new Date(new Date(c.createdAt).getTime()+7*86400000).toISOString())]].map(([a,b])=><div key={a}><small>{t(a)}</small><strong>{b}</strong></div>)}<div><small>{t('SLA status')}</small>{sla(c)}</div></div><a className="map-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(mapQuery)}`} target="_blank" rel="noreferrer"><MapPin size={14}/>{t('View location on map')}</a><p className="sla-note">{t('SLA clock starts when reported; reopening keeps the original deadline.')}</p><h3>{t('Resolution details')}</h3><p>{c.resolution||t('Not resolved yet')}</p>{c.resolutionPhoto?<Photo id={c.id} photo={c.resolutionPhoto} t={t}/>:c.resolvedAt&&<p className="sla-note">{t('No photo attached to this earlier resolution.')}</p>}
 <form onSubmit={submit}><h3>{t('Update complaint')}</h3><div className="form-grid"><label>{t('Assigned officer')}<select value={officer} onChange={e=>setOfficer(e.target.value)} required={status!=='New'}>{['',...officers].map(o=><option key={o} value={o}>{o||t('Unassigned')}</option>)}</select></label><label>{t('Status')}<select value={status} onChange={e=>{setStatus(e.target.value);setError('');}}>{[c.status,...transitions[c.status]].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label></div><details className="edit-location"><summary>{t('Edit complaint location')}</summary><LocationFields t={t} c={c}/></details><label>{t(resolving?'Resolution details':'Activity note / resolution details')}<textarea required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder={t('Describe the action taken…')}/></label>
 {resolving&&<div className="photo-upload"><label htmlFor="resolution-photo"><span><Upload size={16}/>{t('Resolution photo')} <b>*</b></span><small>{t('Upload a photo showing the completed repair. JPEG, PNG or WebP · up to 5 MB.')}</small></label><input id="resolution-photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0]||null;setPhoto(null);setError('');if(f&&(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)){setError(t('Choose a JPEG, PNG or WebP photo up to 5 MB.'));e.target.value='';return;}setPhoto(f);}}/>{preview&&<div className="upload-preview"><img src={preview} alt={t('Selected repair photo')} onError={()=>{setPhoto(null);setError(t('This image cannot be opened. Choose another photo.'));}}/><span>{photo?.name}</span><button type="button" className="text-button" onClick={()=>{setPhoto(null);const input=document.getElementById('resolution-photo') as HTMLInputElement;if(input)input.value='';}}>{t('Remove photo')}</button></div>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={saving||!!error||(resolving&&!photo)}>{t(saving?'Saving…':resolving?'Submit as resolved':'Save update')}</button></form>
 <h3>{t('Activity & history')}</h3><div className="timeline">{[...c.history].reverse().map((h,i)=><div key={i}><i/><strong>{t(h.action)}</strong><small>{date(h.at)} · {new Date(h.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small><p>{h.note}</p>{h.photo&&<Photo id={c.id} photo={h.photo} t={t}/>}</div>)}</div></div></Dialog>;
}
export function NewDialog({t,saving,close,save}:{t:Translate;saving:boolean;close:()=>void;save:SaveComplaint}){
 return <Dialog close={close} title={t('New complaint')}><form className="dialog-body" onSubmit={e=>{e.preventDefault();save(Object.fromEntries(new FormData(e.currentTarget)),'POST');}}><label>{t('Title')}<input name="title" required maxLength={500}/></label><label>{t('Issue category')}<select name="category">{categories.map(c=><option key={c} value={c}>{t(c)}</option>)}</select></label><LocationFields t={t}/><div className="form-grid"><label>{t('Citizen name')}<input name="citizen" required maxLength={500}/></label><label>{t('Priority')}<select name="priority">{['Normal','High','Critical'].map(c=><option key={c} value={c}>{t(c)}</option>)}</select></label></div><div className="form-actions"><button type="button" className="button" onClick={close}>{t('Cancel')}</button><button className="button primary" disabled={saving}>{t(saving?'Saving…':'Register complaint')}</button></div></form></Dialog>;
}
