'use client';
import {useEffect,useRef,useState} from 'react';
import {Bell,LogOut,X,ChevronRight} from 'lucide-react';
import type {Complaint} from '../lib/domain';
import {matchesRisk,selectComplaints,emptyFilters,type Risk} from '../lib/operations';
export function HeaderActions({items,now,t,onOpen}:{items:Complaint[];now:number;t:(s:string)=>string;onOpen:(c:Complaint)=>void}){
 const [open,setOpen]=useState(false),[readAt,setReadAt]=useState(0);
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{setReadAt(Number(localStorage.getItem('up-notifications-read'))||0);},[]);
 useEffect(()=>{if(!open)return;const click=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key);};},[open]);
 const alerts=selectComplaints(items.filter(c=>(['critical','overdue','near','escalated','unassigned'] as Risk[]).some(risk=>matchesRisk(c,risk,now))),emptyFilters,now);
 const unread=alerts.filter(c=>{const created=new Date(c.createdAt).getTime();return Math.max(new Date(c.updatedAt).getTime(),created+5*86400000<=now?created+5*86400000:0,created+7*86400000<=now?created+7*86400000:0)>readAt;}).length;
 function reason(c:Complaint){return matchesRisk(c,'critical',now)?'Critical':matchesRisk(c,'overdue',now)?'Overdue':matchesRisk(c,'escalated',now)?'Escalated':matchesRisk(c,'unassigned',now)?'Unassigned':'Due within 48 hours';}
 return <><div className="notification-root" ref={root}><button ref={trigger} className="icon-button notification-toggle" aria-label={`${t('Notifications')}${unread?` (${unread})`:''}`} aria-expanded={open} aria-controls="notifications" onClick={()=>setOpen(!open)}><Bell size={19}/>{unread>0&&<span className="notification-dot"/>}</button>{open&&<section className="notification-panel" id="notifications" aria-label={t('Notifications')}><header><div><h2>{t('Notifications')}</h2><p>{t('Cases requiring your attention')}</p></div><button className="icon-button" aria-label={t('Close notifications')} onClick={()=>{setOpen(false);trigger.current?.focus();}}><X size={17}/></button></header>{alerts.length>0?<><div className="notification-list">{alerts.map(c=><button key={c.id} className="notification-item" onClick={()=>{setOpen(false);onOpen(c);}}><span><small>{c.id} · {t(reason(c))}</small><strong>{t(c.title)}</strong><span>{t(c.district)}</span></span><ChevronRight size={16}/></button>)}</div><button className="text-button mark-read" onClick={()=>{const time=Date.now();setReadAt(time);localStorage.setItem('up-notifications-read',String(time));}}>{t('Mark all as read')}</button></>:<p className="notification-empty">{t('All caught up. No cases need attention.')}</p>}</section>}</div><form action="/api/logout" method="post" className="logout-form"><button className="button logout-button" type="submit" title={t('Log out')}><LogOut size={16}/><span>{t('Log out')}</span></button></form></>;
}
